name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export GIT_HASH=$(git rev-parse HEAD)
        docker build \
          --bulid-arg GIT_HASH=${GIT_HASH::7} \
          . \
          --file Dockerfile \
          --tag movie-recommender:$(date +%s)
